[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[window]
decorations = "None"
startup_mode = "Windowed"
dynamic_padding = true
padding = { x = 0, y = 0 }
blur = true
opacity = 1.0

# Font section
[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 12

# Color section
[colors]
draw_bold_text_with_bright_colors = false

[general]
import = [
    "themes/material_design.toml"
]
